title: "How We Build AGI: ARU"
description: "Проект ARU-AGI от Архитектора"
theme: minima
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      layout: default
      css: /assets/styles.css
